DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS TITLE;
DROP TABLE IF EXISTS RUNTIME;
DROP TABLE IF EXISTS CREW;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    title TEXT NOT NULL,
    genre TEXT,
    minutes int,
    actor text
);

CREATE TABLE TITLE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL

);

CREATE TABLE RUNTIME (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    minutes INTEGER NOT NULL

);

CREATE TABLE CREW (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Actor TEXT NOT NULL
);
